# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/95ace9a5-b2dd-4ed2-b5fe-c66f59979916";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:1" "noatime" "discard=async" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/95ace9a5-b2dd-4ed2-b5fe-c66f59979916";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:1" "noatime" "discard=async" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/95ace9a5-b2dd-4ed2-b5fe-c66f59979916";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd:1" "noatime" "discard=async" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D176-EA4B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b09731de-c722-49b1-954e-5443f0697cb2"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
